"use client";

import { motion } from "framer-motion";
import { Bot, Check, CheckCircle2, CircleDot, FileText, FolderOpen, Search, ShieldCheck, Sparkles, Timer, UserRound, Waypoints } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type State = "Completed" | "Working" | "Queued" | "Awaiting";
type Stage = { id: string; name: string; state: State; summary: string; operation: string; inputs: string[]; output: string };
const stages: Stage[] = [
  { id: "curator", name: "Case File Curator", state: "Completed", summary: "Curates participant material and prepares the source index.", operation: "Material curation completed.", inputs: ["Supplied participant material"], output: "Canonical source index" },
  { id: "collector", name: "Evidence Collector", state: "Completed", summary: "Extracts and classifies source-backed evidence.", operation: "Evidence collection completed.", inputs: ["Canonical source index"], output: "Evidence items with source references" },
  { id: "suspect", name: "Suspect Analyst", state: "Working", summary: "Compares case-derived profiles and structured claims.", operation: "Reviewing supported and unknown claims.", inputs: ["E-01", "E-04"], output: "Waiting for analysis to complete" },
  { id: "timeline", name: "Timeline Reconciler", state: "Working", summary: "Aligns events and flags inconsistencies across sources.", operation: "Cross-referencing event dates across sources.", inputs: ["E-01", "E-03"], output: "Waiting for analysis to complete" },
  { id: "skeptic", name: "Skeptic", state: "Queued", summary: "Challenges structured specialist outputs after both analyses finish.", operation: "Waiting for both parallel specialists.", inputs: ["Specialist outputs"], output: "Not available yet" },
  { id: "detective", name: "Lead Detective", state: "Queued", summary: "Synthesizes permitted findings into a proposal.", operation: "Waiting for Skeptic review.", inputs: ["Approved specialist outputs"], output: "Not available yet" },
  { id: "review", name: "Human Review", state: "Awaiting", summary: "Records the human decision on a proposed verdict.", operation: "Awaiting agent output.", inputs: ["Proposed verdict"], output: "Not available yet" },
];
const nav = [["Overview", FolderOpen, "/case/overview"], ["Evidence", FileText, "/case/evidence"], ["Timeline", Timer, "/case/timeline"], ["Analysis", Waypoints, "/case/analysis"], ["Agent Workspace", Bot, "/agent-workspace"], ["Proposed verdict", ShieldCheck, "#"]] as const;

export function AgentWorkspace() { const [selected, setSelected] = useState<Stage>(stages[3]); const [filter, setFilter] = useState("all"); const activities = filter === "all" ? stages : stages.filter((stage) => stage.id === filter); return <main className="min-h-[100dvh] bg-[#24160e] text-[#f8ebd2]"><div className="paper-noise pointer-events-none fixed inset-0" /><div className="relative grid min-h-[100dvh] lg:grid-cols-[250px_minmax(0,1fr)]"><Sidebar /><div className="min-w-0"><Topbar /><section className="px-4 py-6 sm:px-7 lg:px-6"><div className="mx-auto grid max-w-[1450px] gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div><Header /><Workflow selected={selected} select={setSelected} /><StageDetail stage={selected} /></div><Activity activities={activities} filter={filter} setFilter={setFilter} select={setSelected} /></div></section></div></div></main>; }
function Sidebar() { return <aside className="hidden border-r border-[#745022]/65 bg-[#24160e] p-5 lg:flex lg:flex-col"><Link href="/" className="flex items-center gap-3 font-serif text-[28px] font-semibold tracking-wide"><span className="grid size-9 place-items-center rounded-lg border border-[#f4b941]/60 text-xl text-[#f4b941]">S</span>Sherlok</Link><p className="mt-1 text-sm text-[#d8c4a0]">AI agents for deeper answers</p><nav className="mt-8 space-y-1" aria-label="Case navigation">{nav.map(([label, Icon, href]) => <Link key={label} href={href} aria-current={label === "Agent Workspace" ? "page" : undefined} className={`flex items-center gap-3 rounded-lg px-3 py-3 text-sm transition ${label === "Agent Workspace" ? "border-l-2 border-[#f4b941] bg-[#5a3b18]/70 font-semibold text-[#f4b941]" : "hover:bg-[#f8ebd2]/10"}`}><Icon className="size-5" strokeWidth={1.6} />{label}</Link>)}</nav><p className="mt-auto border-t border-[#745022] pt-6 font-serif text-lg italic text-[#e9d8bb]">Building clearer truths,<br />together.</p></aside>; }
function Topbar() { return <header className="flex min-h-[76px] items-center gap-4 border-b border-[#745022] px-4 sm:px-7 lg:px-6"><label className="hidden max-w-[520px] flex-1 items-center gap-3 rounded-lg border border-[#745022] bg-[#382315] px-4 py-3 text-[#d8c4a0] md:flex"><Search className="size-5 text-[#f4b941]" /><span className="text-sm">Search evidence, claims, or questions…</span></label><div className="ml-auto flex items-center gap-2 text-sm font-semibold text-[#18afa3]"><span className="size-2.5 rounded-full bg-[#18afa3]" />Investigation in progress</div><div className="hidden rounded-lg border border-[#745022] bg-[#382315] px-4 py-2.5 text-sm font-semibold sm:block">Gemini</div></header>; }
function Header() { return <header className="mb-4 flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow text-[#f4b941]">Agent workspace</p><h1 className="mt-1 font-serif text-4xl font-semibold sm:text-5xl">Agent Workspace</h1><p className="mt-2 flex items-center gap-2 text-[#d8c4a0]"><span className="size-3 rounded-full bg-[#f4b941]" />Watch the investigation unfold</p></div><section className="flex gap-3 rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-4 text-[#1e2831]"><Waypoints className="size-8 text-[#745022]" /><div><b className="font-serif text-xl">Parallel specialist analysis</b><p className="mt-1 text-sm text-[#5c5145]">Independent roles are working in parallel.</p></div></section></header>; }
function Workflow({ selected, select }: { selected: Stage; select: (stage: Stage) => void }) { return <section className="rounded-lg border border-[#745022] bg-[#1c120c]/80 p-4 sm:p-6"><h2 className="sr-only">Investigation workflow</h2><div className="grid gap-4 lg:grid-cols-[1fr_1fr_1.35fr_1fr_1fr_1fr] lg:items-center">{stages.map((stage, index) => <motion.div key={stage.id} initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: index * .05 }} className="relative flex items-center gap-3 lg:block"><button onClick={() => select(stage)} className={`relative z-10 w-full rounded-lg border p-4 text-left transition ${selected.id === stage.id ? "border-[#f4b941] bg-[#5a3b18]/65 ring-1 ring-[#f4b941]" : stage.state === "Working" ? "border-[#f4b941] bg-[#382315]" : stage.state === "Completed" ? "border-[#18afa3] bg-[#18afa3]/10" : stage.state === "Awaiting" ? "border-[#7b4696] bg-[#7b4696]/10" : "border-[#b89b6e] bg-[#382315]"}`}><span className="flex items-center gap-2"><StageIcon state={stage.state} /><b className="text-sm">{stage.name}</b></span><span className={`mt-2 block text-xs font-semibold ${stateText(stage.state)}`}>{stage.state}</span></button>{index < stages.length - 1 && <span className="hidden lg:block lg:absolute lg:left-full lg:top-1/2 lg:h-px lg:w-4 lg:bg-[#b89b6e]" />}</motion.div>)}</div><div className="mt-5 border-t border-[#745022] pt-4"><ol className="grid grid-cols-3 gap-3 text-center sm:grid-cols-6">{["Prepare", "Collect", "Analyze", "Challenge", "Synthesize", "Review"].map((phase, index) => <li key={phase} className="text-xs"><span className={`mx-auto mb-2 grid size-5 place-items-center rounded-full border ${index < 2 ? "border-[#18afa3] bg-[#18afa3] text-white" : index === 2 ? "border-[#f4b941] bg-[#f4b941] text-[#24160e]" : "border-[#b89b6e]"}`}>{index < 2 ? <Check className="size-3" /> : ""}</span>{phase}</li>)}</ol></div><ol className="sr-only">{stages.map((stage) => <li key={stage.id}>{stage.name}: {stage.state}. {stage.summary}</li>)}</ol></section>; }
function StageIcon({ state }: { state: State }) { return state === "Completed" ? <CheckCircle2 className="size-5 text-[#18afa3]" /> : state === "Working" ? <CircleDot className="size-5 text-[#f4b941]" /> : state === "Awaiting" ? <Timer className="size-5 text-[#c184df]" /> : <CircleDot className="size-5 text-[#d8c4a0]" />; }
function stateText(state: State) { return state === "Completed" ? "text-[#56e1d4]" : state === "Working" ? "text-[#f6cc6c]" : state === "Awaiting" ? "text-[#d9a7eb]" : "text-[#d8c4a0]"; }
function StageDetail({ stage }: { stage: Stage }) { return <section className="mt-4 rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-5 text-[#1e2831]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#d8c4a0] pb-4"><h2 className="font-serif text-2xl font-semibold">Selected stage</h2><span className="flex items-center gap-2"><b className="font-serif text-xl">{stage.name}</b><span className={`rounded-full px-3 py-1 text-xs font-bold ${stage.state === "Working" ? "bg-[#f6deaa] text-[#704a00]" : "bg-[#d5f0e8] text-[#006b54]"}`}>{stage.state}</span></span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Detail icon={UserRound} title="Responsibility" text={stage.summary} /><Detail icon={Sparkles} title="Current operation" text={stage.operation} /><Detail icon={FileText} title="Inputs" text={stage.inputs.join(" · ")} /><Detail icon={FileText} title="Outputs" text={stage.output} /></div></section>; }
function Detail({ icon: Icon, title, text }: { icon: typeof UserRound; title: string; text: string }) { return <div className="rounded-lg border border-[#d8c4a0] bg-[#fff8e9] p-4"><div className="flex gap-3"><Icon className="size-6 shrink-0 text-[#745022]" /><div><h3 className="font-serif text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-5 text-[#5c5145]">{text}</p></div></div></div>; }
function Activity({ activities, filter, setFilter, select }: { activities: Stage[]; filter: string; setFilter: (value: string) => void; select: (stage: Stage) => void }) { return <aside className="border-[#745022] xl:border-l xl:pl-5"><div className="flex items-center justify-between gap-3"><h2 className="font-serif text-2xl">Activity</h2><Select value={filter} onValueChange={setFilter}><SelectTrigger className="h-9 w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All activity</SelectItem>{stages.map((stage) => <SelectItem key={stage.id} value={stage.id}>{stage.name}</SelectItem>)}</SelectContent></Select></div><div className="mt-4 space-y-2" aria-live="polite">{activities.map((stage) => <button onClick={() => select(stage)} key={stage.id} className="w-full rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-4 text-left text-[#1e2831] transition hover:border-[#f4b941]"><div className="flex gap-3"><StageIcon state={stage.state} /><div className="min-w-0"><b className="block text-sm">{stage.name}</b><span className={`block text-xs font-semibold ${stage.state === "Working" ? "text-[#704a00]" : "text-[#006b54]"}`}>{stage.state}</span><p className="mt-1 text-xs leading-5 text-[#5c5145]">{stage.operation}</p></div></div></button>)}</div><section className="mt-4 rounded-lg border border-[#745022] bg-[#382315] p-4"><div className="flex gap-3"><ShieldCheck className="size-6 text-[#f4b941]" /><div><b>No errors requiring attention</b><p className="mt-1 text-sm leading-5 text-[#d8c4a0]">All visible stages are operating as expected.</p></div></div></section></aside>; }
