"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, CircleAlert, FileText, FolderOpen, ListFilter, MoreHorizontal, Search, ShieldCheck, SlidersHorizontal, Timer, Waypoints, Bot, Scale, X } from "lucide-react";
import Link from "next/link";
import { SherlokMark } from "@/components/investigation/sherlok-mark";
import type { components } from "@/lib/generated/investigation-api.v1";

type CaseFile = components["schemas"]["CaseFile"];
type Evidence = components["schemas"]["EvidenceItem"];
const nav = [["Overview", FolderOpen, "overview"], ["Evidence", FileText, "evidence"], ["Timeline", Timer, "timeline"], ["Analysis", Waypoints, "analysis"], ["Agent Workspace", Bot, "agents"], ["Proposed Verdict", Scale, "verdict"]] as const;

export function EvidenceDossier({ caseFile, investigationId, isComplete }: { caseFile: CaseFile; investigationId: string; isComplete: boolean }) {
  const evidence = caseFile.evidence ?? [];
  const sources = sourceNames(caseFile);
  const [query, setQuery] = useState(""); const [classification, setClassification] = useState("all"); const [source, setSource] = useState("all"); const [selectedId, setSelectedId] = useState(evidence[0]?.id ?? "");
  const filtered = useMemo(() => evidence.filter((item) => (classification === "all" || item.classification === classification) && (source === "all" || item.source_references.some((reference) => reference.source_name === source)) && `${item.id} ${item.statement}`.toLowerCase().includes(query.toLowerCase())), [classification, evidence, query, source]);
  const selected = evidence.find((item) => item.id === selectedId) ?? filtered[0];
  const href = (route: string) => route === "agents" ? `/agent-workspace?investigation_id=${encodeURIComponent(investigationId)}` : `/case/${route}?investigation_id=${encodeURIComponent(investigationId)}`;
  const hasFilters = Boolean(query || classification !== "all" || source !== "all");

  useEffect(() => {
    const focusHashTarget = () => {
      const evidenceId = evidenceIdFromHash(window.location.hash);
      if (!evidenceId || !evidence.some((item) => item.id === evidenceId)) return;
      setSelectedId(evidenceId);
      window.requestAnimationFrame(() => document.getElementById(`evidence-${evidenceId}`)?.focus());
    };

    focusHashTarget();
    window.addEventListener("hashchange", focusHashTarget);
    return () => window.removeEventListener("hashchange", focusHashTarget);
  }, [evidence]);

  return <main className="min-h-[100dvh] bg-[#24160e] text-[#f8ebd2]"><div className="paper-noise pointer-events-none fixed inset-0" /><div className="relative grid min-h-[100dvh] lg:grid-cols-[228px_minmax(0,1fr)]">
    <aside className="hidden border-r border-[#745022]/65 bg-[#24160e]/95 p-6 lg:flex lg:flex-col"><Link href="/" className="flex items-center gap-3 font-serif text-[34px] font-semibold leading-none"><SherlokMark />Sherlok</Link><nav className="mt-10 space-y-1" aria-label="Case navigation">{nav.map(([label, Icon, route]) => <Link key={route} href={href(route)} aria-current={route === "evidence" ? "page" : undefined} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-sm ${route === "evidence" ? "border-l-2 border-[#f4b941] bg-[#5a3b18]/70 font-semibold text-[#f4b941]" : "text-[#f8ebd2] hover:bg-white/10"}`}><Icon className="size-5" />{label}</Link>)}</nav><p className="mt-auto border-b-2 border-[#f4b941] pb-5 font-serif text-lg italic">A clearer<br />picture, together.</p></aside>
    <div className="min-w-0"><header className="flex h-[72px] items-center gap-5 border-b border-[#745022] bg-[#24160e]/95 px-6"><label className="flex max-w-[988px] flex-1 items-center gap-4 rounded-lg border border-[#745022] bg-[#382315] px-3 py-3 text-[#d8c4a0]"><Search className="size-5" /><input aria-label="Search evidence" className="w-full bg-transparent text-sm outline-none placeholder:text-[#d8c4a0]" placeholder="Search evidence…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="hidden items-center gap-3 text-[#f8ebd2] md:flex"><SlidersHorizontal className="size-5" /><span className="rounded-lg border border-[#745022] px-5 py-3 text-sm">Case file</span></div></header>
      <section className="px-6 py-5"><div className="mx-auto grid max-w-[1320px] gap-6 xl:grid-cols-[minmax(0,1fr)_255px]"><div><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-serif text-[40px] font-semibold leading-none">Evidence</h1><p className="mt-1 font-serif text-xl text-[#e9d8bb]">Trace every item to its source</p></div><div className="flex flex-wrap gap-3"><Select label="Classification" value={classification} onChange={setClassification} options={[["all", "All classifications"], ["observed_fact", "Observed facts"], ["inference", "Inferences"]]} /><Select label="Source" value={source} onChange={setSource} options={[["all", "All sources"], ...sources.map((name) => [name, name])]} /><span className="flex items-center gap-3 rounded-lg border border-[#745022] px-4 py-3 text-sm">Source order <ChevronDown className="size-4" /></span></div></header>
        <SourcePanel sources={sources} caseFile={caseFile} href={href("overview")} />
        {evidence.length ? <EvidenceTable items={filtered} selectedId={selected?.id} onSelect={setSelectedId} /> : null}
        {selected ? <EvidenceDetail item={selected} onClose={() => setSelectedId("")} /> : null}
        {!evidence.length || !filtered.length ? <NoEvidence complete={isComplete} hasFilters={hasFilters} clear={() => { setQuery(""); setClassification("all"); setSource("all"); }} /> : null}
      </div><RightRail caseFile={caseFile} complete={isComplete} href={href("analysis")} /></div></section>
    </div></div></main>;
}

function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <label className="relative"><span className="sr-only">{label}</span><select aria-label={label} className="appearance-none rounded-lg border border-[#745022] bg-[#24160e] py-3 pl-4 pr-10 text-sm text-[#f8ebd2]" value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 size-4" /></label>; }
function SourcePanel({ sources, caseFile, href }: { sources: string[]; caseFile: CaseFile; href: string }) { return <section className="mt-6 rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-4 text-[#1e2831]"><h2 className="flex items-center gap-3 font-serif text-xl font-semibold"><FileText className="size-6" />Source material</h2>{sources.length ? sources.map((name) => <Link href={href} key={name} className="mt-3 flex items-center gap-5 rounded-lg border border-[#d8c4a0] p-4 hover:bg-[#f4e8d0]"><span className="grid size-20 place-items-center border border-[#b89b6e] bg-[#f4e8d0]"><FileText className="size-9" /></span><span className="flex-1"><b className="block font-serif text-lg">{name}</b><span className="text-sm">Participant material · {caseFile.material_blocks?.filter((block) => block.source_reference.source_name === name).length ?? 1} canonical blocks</span></span><span className="rounded-md border border-[#b89b6e] px-3 py-2 text-sm font-semibold">Open material</span></Link>) : <p className="mt-3 text-sm text-[#5c5145]">Material is still being prepared.</p>}</section>; }
function EvidenceTable({ items, selectedId, onSelect }: { items: Evidence[]; selectedId?: string; onSelect: (id: string) => void }) { return <div className="mt-3 overflow-x-auto rounded-lg border border-[#745022]"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[#745022] text-[#e9d8bb]"><tr><th className="w-12 p-4">ID</th><th className="p-4">Statement</th><th className="p-4">Classification</th><th className="p-4">Source reference</th><th className="p-4"><span className="sr-only">Open detail</span></th></tr></thead><tbody>{items.map((item) => <tr id={`evidence-${item.id}`} key={item.id} tabIndex={-1} className={`border-b border-[#745022]/70 outline-none last:border-0 focus:bg-[#145149]/55 focus:outline focus:outline-2 focus:outline-[#f4b941] ${item.id === selectedId ? "bg-[#145149]/55 outline outline-1 outline-[#18afa3]" : "hover:bg-[#382315]"}`}><td className="p-4 font-mono font-semibold">{item.id}</td><td className="max-w-[320px] p-4 leading-5">{item.statement}</td><td className="p-4"><Badge classification={item.classification} /></td><td className="p-4">{item.source_references[0] ? <span className="flex items-center gap-2"><FileText className="size-5" />{referenceLabel(item.source_references[0])}</span> : <span className="text-[#d8c4a0]">Source reference pending</span>}</td><td className="p-4"><button aria-label={`Inspect Evidence ${item.id}`} className="rounded p-1 hover:bg-[#5a3b18] focus:outline focus:outline-2 focus:outline-[#f4b941]" onClick={() => onSelect(item.id)} type="button"><MoreHorizontal className="size-5" /></button></td></tr>)}</tbody></table></div>; }
function Badge({ classification }: { classification: Evidence["classification"] }) { const fact = classification === "observed_fact"; return <span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold ${fact ? "border-[#18afa3] bg-[#006b54]/50 text-[#64f3e6]" : "border-[#f4b941] bg-[#704a00]/50 text-[#ffd66d]"}`}><span className="size-2.5 rounded-full bg-current" />{fact ? "Observed fact" : "Inference"}</span>; }
function EvidenceDetail({ item, onClose }: { item: Evidence; onClose: () => void }) { return <section className="mt-3 rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-5 text-[#1e2831]"><header className="flex items-center gap-4 border-b border-[#d8c4a0] pb-3"><h2 className="font-serif text-2xl font-semibold">{item.id}</h2><Badge classification={item.classification} /><button aria-label="Close evidence detail" className="ml-auto" onClick={onClose}><X /></button></header><div className="grid gap-5 pt-5 md:grid-cols-[1.5fr_1fr_1fr]"><div><h3 className="font-semibold">Statement</h3><p className="mt-2 leading-6">{item.statement}</p><h3 className="mt-5 border-t border-[#d8c4a0] pt-4 font-semibold">Details</h3><p className="mt-2 leading-6 text-[#514e4b]">This agent-produced evidence item is read-only and traceable to participant material.</p></div><div className="border-[#d8c4a0] md:border-l md:pl-5"><h3 className="font-semibold">Source reference</h3>{item.source_references.length ? item.source_references.map((reference, index) => <p className="mt-3 flex gap-2" key={index}><FileText className="size-5 shrink-0" /><span>{referenceLabel(reference)}</span></p>) : <p className="mt-2 text-sm text-[#5c5145]">A source reference has not been supplied.</p>}</div><div className="border-[#d8c4a0] md:border-l md:pl-5"><h3 className="font-semibold">Traceability path</h3><ol className="mt-3 space-y-3 text-sm"><li className="flex gap-2"><Check className="size-5 rounded-full bg-[#18afa3] p-1 text-white" />Supplied source</li><li className="flex gap-2"><Check className="size-5 rounded-full bg-[#18afa3] p-1 text-white" />Canonical block</li><li className="flex gap-2"><Check className="size-5 rounded-full bg-[#18afa3] p-1 text-white" />Evidence item</li></ol></div></div></section>; }
function RightRail({ caseFile, complete, href }: { caseFile: CaseFile; complete: boolean; href: string }) { return <aside className="space-y-4"><section className="rounded-lg border border-[#745022] bg-[#24160e]/85 p-5"><h2 className="flex items-center gap-3 border-b border-[#745022] pb-4 font-serif text-xl"><ShieldCheck className="text-[#31daca]" />Evidence Collector</h2><div className="mt-5 flex items-center gap-4"><span className="grid size-14 place-items-center rounded-full border-4 border-[#18afa3]"><Check className="text-[#31daca]" /></span><b className="text-lg text-[#31daca]">{complete ? "Completed" : "Working"}</b></div><p className="mt-4 text-sm leading-5">{complete ? "All available sources have been processed and evidence items extracted." : "Evidence collection is continuing against the available material."}</p><ul className="mt-5 space-y-3 text-sm">{["Sources ingested", "Evidence extracted", "Classifications applied", "Source references checked", "Ready for analysis"].map((item) => <li className="flex gap-3" key={item}><Check className="size-5 rounded-full bg-[#18afa3] p-1 text-[#24160e]" />{item}</li>)}</ul></section>{caseFile.material_warnings?.length ? <section className="rounded-lg border border-[#a4493f] bg-[#432015] p-5"><h2 className="flex items-center gap-3 text-lg font-semibold text-[#ff9a91]"><CircleAlert />Material warning</h2><p className="mt-4 text-sm leading-5">{caseFile.material_warnings.join(" ")}</p></section> : null}<section className="rounded-lg border border-[#745022] bg-[#24160e]/85 p-5"><h2 className="flex items-center gap-3 border-b border-[#745022] pb-4 font-serif text-xl"><ListFilter />Next step</h2><Link href={href} className="mt-5 flex items-center gap-3 font-semibold text-[#f4b941]">Review specialist analysis <ChevronDown className="-rotate-90" /></Link><p className="mt-2 pl-9 text-sm leading-5">Analyze how the evidence supports or conflicts with key claims.</p></section></aside>; }
function NoEvidence({ complete, hasFilters, clear }: { complete: boolean; hasFilters: boolean; clear: () => void }) { const title = hasFilters ? "No Evidence matches those filters" : complete ? "No collected evidence" : "Evidence collection is in progress"; const message = hasFilters ? "Try a different search or clear the current filters." : complete ? "Evidence collection completed without producing displayable Evidence items." : "Collected Evidence will appear here when it is available."; return <section className="mt-3 rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-8 text-center text-[#1e2831]"><h2 className="font-serif text-2xl">{title}</h2><p className="mt-2">{message}</p>{hasFilters && <button className="mt-4 rounded border border-[#745022] px-4 py-2 font-semibold" onClick={clear}>Clear filters</button>}</section>; }
function sourceNames(caseFile: CaseFile) { return [...new Set([...(caseFile.material_blocks ?? []).map((block) => block.source_reference.source_name), ...(caseFile.evidence ?? []).flatMap((item) => item.source_references.map((reference) => reference.source_name))].filter(Boolean))]; }
function referenceLabel(reference: components["schemas"]["SourceReference"]) { const location = [reference.heading, reference.page && `page ${reference.page}`, reference.paragraph && `paragraph ${reference.paragraph}`, reference.list_position].filter(Boolean).join(", "); return location ? `${reference.source_name} · ${location}` : reference.source_name || "Source location available"; }
function evidenceIdFromHash(hash: string) { const prefix = "#evidence-"; if (!hash.startsWith(prefix)) return null; const encodedId = hash.slice(prefix.length); try { return decodeURIComponent(encodedId); } catch { return null; } }
