"use client";

import Link from "next/link";
import { useState } from "react";
import { AlertTriangle, Bot, Check, CircleHelp, Clock3, FileText, FolderOpen, Scale, Waypoints } from "lucide-react";

import { SherlokMark } from "@/components/investigation/sherlok-mark";
import type { components } from "@/lib/generated/investigation-api.v1";

type CaseFile = components["schemas"]["CaseFile"];
type TimelineEvent = components["schemas"]["TimelineEvent"];
type TimelineIssue = components["schemas"]["TimelineIssue"];

const navigation = [["Overview", FolderOpen, "overview"], ["Evidence", FileText, "evidence"], ["Timeline", Clock3, "timeline"], ["Analysis", Waypoints, "analysis"], ["Agent Workspace", Bot, "agents"], ["Proposed Verdict", Scale, "verdict"]] as const;

export function TimelineDossier({ caseFile, investigationId, isComplete }: { caseFile: CaseFile; investigationId: string; isComplete: boolean }) {
  const events = caseFile.timeline?.events ?? [];
  const chronology = events.filter(isChronologicalEvent);
  const uncertainEvents = events.filter((event) => !isChronologicalEvent(event));
  const issues = caseFile.timeline?.issues ?? [];
  const [selectedEvent, setSelectedEvent] = useState<TimelineEvent | undefined>(chronology[0] ?? uncertainEvents[0]);

  return <main className="min-h-[100dvh] bg-[#24160e] text-[#f8ebd2]"><div className="paper-noise pointer-events-none fixed inset-0" /><div className="relative grid min-h-[100dvh] lg:grid-cols-[228px_minmax(0,1fr)]"><CaseNavigation investigationId={investigationId} /><div className="min-w-0"><header className="flex min-h-[74px] items-center border-b border-[#745022] px-6"><p className="text-sm font-semibold" role="status">{isComplete ? "Investigation complete" : "Timeline reconciliation in progress"}</p></header><section className="px-6 py-5"><div className="mx-auto max-w-[1320px]"><header className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="font-serif text-[42px] font-semibold leading-none">Timeline</h1><p className="mt-1 font-serif text-2xl text-[#e9d8bb]">Events, gaps, and contradictions</p></div><p className="rounded-lg border border-[#d8c4a0] bg-[#fbf2de] px-5 py-4 font-serif text-xl text-[#1e2831]">Timeline Reconciler · {isComplete ? "Completed" : "Working"}</p></header><TimelineContent chronology={chronology} uncertainEvents={uncertainEvents} issues={issues} isComplete={isComplete} investigationId={investigationId} selectedEvent={selectedEvent} onSelect={setSelectedEvent} /></div></section></div></div></main>;
}

function TimelineContent({ chronology, uncertainEvents, issues, isComplete, investigationId, selectedEvent, onSelect }: { chronology: TimelineEvent[]; uncertainEvents: TimelineEvent[]; issues: TimelineIssue[]; isComplete: boolean; investigationId: string; selectedEvent?: TimelineEvent; onSelect: (event: TimelineEvent) => void }) {
  if (!chronology.length && !uncertainEvents.length && !issues.length) return <section className="mt-5 rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-6 text-[#1e2831]" aria-live="polite"><h2 className="font-serif text-2xl font-semibold">{isComplete ? "No timeline results reported" : "Timeline reconciliation is in progress"}</h2><p className="mt-2">{isComplete ? "The Timeline Reconciler did not report events or open issues." : "Reconciled events and open issues will appear when they are available."}</p></section>;
  return <div className="mt-4 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(330px,.85fr)]"><section className="rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-5 text-[#1e2831]"><EventList title="Chronological events" events={chronology} emptyMessage="No events have a reliable time and order yet." selectedEvent={selectedEvent} onSelect={onSelect} investigationId={investigationId} /><div className="mt-6 border-t-2 border-[#d8c4a0] pt-4"><EventList title="Unordered or uncertain events" description="These events are separate because the reconciler did not establish a reliable time or order." events={uncertainEvents} emptyMessage="No unordered or uncertain events were reported." selectedEvent={selectedEvent} onSelect={onSelect} investigationId={investigationId} /></div></section><aside className="space-y-4"><Issues issues={issues} investigationId={investigationId} /><SelectedEvent event={selectedEvent} investigationId={investigationId} /></aside></div>;
}

function EventList({ title, description, events, emptyMessage, selectedEvent, onSelect, investigationId }: { title: string; description?: string; events: TimelineEvent[]; emptyMessage: string; selectedEvent?: TimelineEvent; onSelect: (event: TimelineEvent) => void; investigationId: string }) {
  return <section><h2 className="font-serif text-2xl font-semibold">{title}</h2>{description ? <p className="mt-1 text-sm text-[#5c5145]">{description}</p> : null}{events.length ? <ol className="mt-4 space-y-3">{events.map((event) => <li className="rounded-lg border border-[#d8c4a0] bg-[#fff8e9]" key={`${event.order}-${event.statement}`}><button aria-pressed={selectedEvent === event} className={`grid w-full gap-4 p-4 text-left sm:grid-cols-[145px_minmax(0,1fr)] ${selectedEvent === event ? "bg-[#eef9f5]" : "hover:bg-[#f4e8d0]"}`} onClick={() => onSelect(event)}><span className="font-serif text-2xl font-semibold">{event.time ?? "Time not established"}</span><span><span className="block text-[17px] leading-6">{event.statement}</span><ClaimStatus status={event.status} /></span></button><EvidenceLinks ids={event.evidence_ids} investigationId={investigationId} /></li>)}</ol> : <p className="mt-3 text-sm text-[#5c5145]">{emptyMessage}</p>}</section>;
}

function ClaimStatus({ status }: { status: TimelineEvent["status"] }) { const supported = status === "supported"; return <span className={`mt-2 inline-flex items-center gap-2 text-sm ${supported ? "text-[#008b79]" : "text-[#5c5145]"}`}>{supported ? <Check className="size-5 rounded-full bg-[#18afa3] p-1 text-white" /> : <CircleHelp className="size-5" />}{supported ? "Supported" : "Unknown"}</span>; }

function Issues({ issues, investigationId }: { issues: TimelineIssue[]; investigationId: string }) { return <section className="rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-4 text-[#1e2831]"><h2 className="font-serif text-2xl font-semibold">Open timeline issues</h2>{issues.length ? <div className="mt-4 space-y-3">{issues.map((issue) => <article className="rounded-lg border border-[#d8c4a0] p-4" key={issue.statement}><h3 className="flex items-center gap-3 font-serif text-xl font-semibold"><AlertTriangle className="size-7 text-[#8b6100]" />{issue.kind === "gap" ? "Gap" : "Contradiction"}</h3><p className="mt-2 leading-5">{issue.statement}</p><EvidenceLinks ids={issue.evidence_ids} investigationId={investigationId} /></article>)}</div> : <p className="mt-3 text-sm text-[#5c5145]">No gaps or contradictions were reported.</p>}</section>; }

function SelectedEvent({ event, investigationId }: { event?: TimelineEvent; investigationId: string }) { return <section className="rounded-lg border border-[#d8c4a0] bg-[#fbf2de] p-4 text-[#1e2831]" aria-live="polite"><h2 className="font-serif text-2xl font-semibold">Selected event details</h2>{event ? <div className="mt-3 rounded-lg border border-[#d8c4a0] p-4"><p className="font-serif text-xl">{event.time ?? "Time not established"}</p><p className="mt-2 leading-5">{event.statement}</p><ClaimStatus status={event.status} /><EvidenceLinks ids={event.evidence_ids} investigationId={investigationId} /></div> : <p className="mt-3 text-sm text-[#5c5145]">Select an event to inspect its citations.</p>}</section>; }

function EvidenceLinks({ ids, investigationId }: { ids: string[]; investigationId: string }) { if (!ids.length) return <p className="border-t border-[#d8c4a0] px-4 py-3 text-sm text-[#5c5145]">No citations supplied.</p>; return <div className="border-t border-[#d8c4a0] px-4 py-3"><p className="text-sm font-semibold">Cited Evidence</p><div className="mt-2 flex flex-wrap gap-2">{ids.map((id) => <Link className="rounded border border-[#745022] px-3 py-1 font-mono text-sm font-semibold text-[#006b54] hover:underline focus:outline focus:outline-2 focus:outline-offset-2 focus:outline-[#006b54]" href={`/case/evidence?investigation_id=${encodeURIComponent(investigationId)}#evidence-${encodeURIComponent(id)}`} key={id}>{id}</Link>)}</div></div>; }

function CaseNavigation({ investigationId }: { investigationId: string }) { return <aside className="hidden border-r border-[#745022]/65 bg-[#24160e]/95 p-6 lg:flex lg:flex-col"><Link href="/" className="flex items-center gap-3 font-serif text-[34px] font-semibold leading-none"><SherlokMark />Sherlok</Link><nav className="mt-8 space-y-1" aria-label="Case navigation">{navigation.map(([label, Icon, route]) => <Link aria-current={route === "timeline" ? "page" : undefined} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-sm ${route === "timeline" ? "border-l-2 border-[#f4b941] bg-[#5a3b18]/70 font-semibold text-[#f4b941]" : "hover:bg-white/10"}`} href={caseHref(route, investigationId)} key={route}><Icon className="size-5" />{label}</Link>)}</nav></aside>; }

function isChronologicalEvent(event: TimelineEvent) { return event.order !== null && event.time !== null; }
function caseHref(route: string, investigationId: string) { const encodedId = encodeURIComponent(investigationId); return route === "agents" ? `/agent-workspace?investigation_id=${encodedId}` : `/case/${route}?investigation_id=${encodedId}`; }
